ur3e_gym: #namespace
    # General Agent parameters
    env_id: "UR3ePegInHoleEnv-v1"
    controller_type: "parallel_position_force" # or "admittance"

    reset_robot: True
    real_robot: False
    test_mode: False

    ft_sensor: True
    relative_to_ee: False
    robot_control_dt: 0.002
    agent_control_dt: 0.05
    reset_time: 2.0
    # actions parameters 
    n_actions: 24
    action_type: "m24"
    object_centric: False
    ee_centric: False

    steps_per_episode: 1000
    
    actor_class: "wave"
    ft_hist: True
    wrench_hist_size: 6
    duration_as_obs: False
    last_action_as_obs: True
    normalize_velocity: True

    rand_seed: 3215   
    rand_interval: 1

    # Curriculum parameters
    initial_curriculum_level: 0.05
    curriculum_level_step: 0.05
    cl_upgrade_level: 0.9
    cl_downgrade_level: 0.2
    cumulative_episode_num: 0 # for linear curriculum
    curriculum_learning: True
    progressive_cl: True
    reward_based_on_cl: True

    # Domain Randomization Parameters
    board_mu: 0.5
    board_mu2: 0
    board_stiffness: 1.0e+5
    max_mu_range: [1, 5]
    max_stiffness_range: [1.0e+5, 1.0e+6]
    max_scale_range: [1.05, 0.99]
    
    ## Target taskboard configuration
    randomize_board_properties: True
    normal_randomization: True
    basic_randomization: False
    # board_initial_pose: [0.17021, -0.36557, 0.35, 0, 0, 0.0] # vertical
    board_initial_pose: [-0.10, 0.38, 0.10, 3.141592, 0, 0.0] # horizontal
    board_workspace: [[-0.05, 0.05], [-0.05, 0.05], [0.08, 0.02], [-20, 20], [-20, 20], [-60, 60]]
    max_board_workspace: [0.08, 0.08, 0.08, 20, 20, 60]
    min_board_workspace: [0.02, 0.02, 0.02, 5, 5, 10]


    ## initial conditions
    random_initial_pose: False
    # for each dimension define upper and lower bound from initial pose
    max_distance: [0.1, 0.1, 0.1, 0.785398, 0.785398, 1.5707]
    workspace: [[-0.1,0.1], [-0.1, 0.1], [0.0, 0.05], [20, -20], [20, -20], [20, -20]]
    init_q: [1.5045, -1.1956, 1.6012, -1.9544, -1.5742, -0.0636]
    
    target_pose: [0.1752261, -0.4610272, 0.4615621, -0.0032208, -0.0006339, 0.9999945, 0.0004608]

    # Reward parameters
    tgt_pose_indices: [0,1,2,3,4,5]
    
    position_threshold: 0.0025 # minimum distance to goal
    max_position_threshold: 0.01   # CL parameter

    reward_type: 'dense-distance-velocity-force'
    termination_on_negative_reward: True
    termination_reward_threshold: -500 # new -500

    cost:
        collision: -500.0
        done: 200
        step: -1.0  # new -1
    w_dist: 1.0
    w_force: 1.0
        
# Controller parameters
ur3e_force_control:
    max_twist: [0.1, 0.1, 0.1, 0.785398, 0.785398, 0.785398]

    max_force_torque: [50, 50.0, 50.0, 4, 4, 4]
    desired_force_torque: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    
    # parallel control parameters
    pd_range_type: 'mult' # or 'sum'
    base_position_kp: [5.0, 5.0, 5.0, 50.0, 50.0, 100.0]
    kpd_range: 5
    base_force_kp: [0.01, 0.01, 0.01, 0.125, 0.125, 0.125]
    kpi_range: 2
    
    alpha: [0.5,0.5,0.5,0.5,0.5,0.5] # keep a degree of compliance