# Joint state controller
joint_state_controller:
  publish_rate: 500
  type: joint_state_controller/JointStateController

scaled_pos_joint_traj_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - shoulder_pan_joint
     - shoulder_lift_joint
     - elbow_joint
     - wrist_1_joint
     - wrist_2_joint
     - wrist_3_joint
  constraints:
    # Default is 0
    goal_time: 0.1
    # Default is 0.01
    stopped_velocity_tolerance: 0.01
    shoulder_pan_joint:
      trajectory: 0
      goal: 0.01
    shoulder_lift_joint:
      trajectory: 0
      goal: 0.01
    elbow_joint:
      trajectory: 0
      goal: 0.01
    wrist_1_joint:
      trajectory: 0
      goal: 0.01
    wrist_2_joint:
      trajectory: 0
      goal: 0.01
    wrist_3_joint:
      trajectory: 0
      goal: 0.01
  gains:
    shoulder_pan_joint: {p: 10000, d: 150, i: 0, i_clamp: 1}
    shoulder_lift_joint: {p: 100000, d: 150, i: 10, i_clamp: 50}
    elbow_joint: {p: 50000, d: 150, i: 1, i_clamp: 25}
    wrist_1_joint: {p: 1000, d: 5, i: 0, i_clamp: 1}
    wrist_2_joint: {p: 750, d: 2, i: 0, i_clamp: 1}
    wrist_3_joint: {p: 250, d: 1, i: 0, i_clamp: 1}

#Position controller
shoulder_pan_joint:
  type: position_controllers/JointPositionController
  joint: shoulder_pan_joint
shoulder_lift_joint:
  type: position_controllers/JointPositionController
  joint: shoulder_lift_joint
elbow_joint:
  type: position_controllers/JointPositionController
  joint: elbow_joint
wrist_1_joint:
  type: position_controllers/JointPositionController
  joint: wrist_1_joint
wrist_2_joint:
  type: position_controllers/JointPositionController
  joint: wrist_2_joint
wrist_3_joint:
  type: position_controllers/JointPositionController
  joint: wrist_3_joint