# gazebo_ros_control:
#   pid_gains:
#     shoulder_pan_joint: {p: 10000, d: 150, i: 0, i_clamp: 1}
#     shoulder_lift_joint: {p: 50000, d: 150, i: 10, i_clamp: 50}
#     elbow_joint: {p: 50000, d: 150, i: 1, i_clamp: 25}
#     wrist_1_joint: {p: 100, d: 5, i: 0, i_clamp: 1}
#     wrist_2_joint: {p: 75, d: 2, i: 0, i_clamp: 1}
#     wrist_3_joint: {p: 25, d: 1, i: 0, i_clamp: 1}